name: Python Developer Tests
on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout tests
        uses: actions/checkout@v2
        with:
          repository: Python-developer-2023/tests
          path: './tests'
          token: ${{ secrets.TOKEN }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Run Tests
        run: |
          python -m tests.${{ github.head_ref }}.main
